### ISSUE TITLE
it it not work with hibernate-gorm

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-flyway#8] opened 2019-03-26 07:47 UTC
my config like this

```
hibernate:
  hbm2ddl:
    auto: update
  show_sql: true
#  dbCreate: create-drop
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL57Dialect
    url: jdbc:mysql://127.0.0.1:3306/micronaut_test
    username: root
    password: root@123

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
```

**Comment by ilopmar** [comment] 2019-04-04 11:38
Can you please provide a sample project that reproduces the issue?

**Comment by jameskleeh** [comment] 2019-04-08 13:21
Closing because of the poor quality of the issue report

**Comment by kastork** [comment] 2019-05-29 19:36
Please re-open.  Hopefully this report and project are good enough to work with.

Here's a project with some notes in the readme [problem demonstrator](https://github.com/kastork/micronaut-gorm-flyway-reproducer)

There seem to be two problems.

1. Gorm sets up the DataSource.  Even if things were working, this would happen before the migration has a chance to run -- admitting the possibility that Gorm would try to interact with the db  before the it is configured.  I think the Liquibase package would suffer this problem as well.

2. The Gorm `DataSource` is not a `NameResolver`, which the Migrator demands. So even if you get the data source naming issues sorted out, you still don't get a migration.

**Closed** 2019-06-13 06:21 UTC
