### ISSUE TITLE
NPE when settings locations

### ISSUE THREAD

**Issue by lucasmogari** [micronaut-projects/micronaut-flyway#6] opened 2019-02-01 18:53 UTC
Hi, I'm following the guide to setup a flyway migration and I'm getting a NPE. I think it's because there are 2 locations methods in org.flywaydb.core.api.configuration.FluentConfiguration. One for strings and other for Location objects, which when it's called, sets all values of locations array to null.

My setup:
IntelliJ
Gradle
Java 1.8
micronaut:1.0.4
micronaut-flyway:1.0.0.RC2

```
java.lang.NullPointerException: null
	at org.flywaydb.core.internal.scanner.Scanner.<init>(Scanner.java:59)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1674)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1341)
	at io.micronaut.configuration.dbmigration.flyway.FlywayStartupEventListener.lambda$run$3(FlywayStartupEventListener.java:110)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
```

Code generated from annotations processor:
```
        var5 = this.getValueForPath(var1, var2, Argument.of(String[].class, "locations"), new String[]{"locations"});
        if (var5.isPresent()) {
            try {
                var4.fluentConfiguration.locations((String[])var5.get());
            } catch (NoSuchMethodError var42) {
            }
        }

        var5 = this.getValueForPath(var1, var2, Argument.of(Location[].class, "locations"), new String[]{"locations"});
        if (var5.isPresent()) {
            try {
                var4.fluentConfiguration.locations((Location[])var5.get());
            } catch (NoSuchMethodError var41) {
            }
        }

```

**Comment by lucasmogari** [comment] 2019-02-01 19:04
If I comment the locations property, and put the migrations scripts in db/migration directory (that is the default), it works.

```
flyway:
  datasources:
    default:
#      locations: classpath:databasemigrations
      validate-on-migrate: true

```

**Comment by ilopmar** [comment] 2019-02-04 09:31
I'm not able to reproduce the issue. Can you please upload a sample application that reproduces it?

**Comment by lucasmogari** [comment] 2019-02-04 10:17
Hi, I investigated a little more now and I think this error happens when using consul.

When I renamed the file bootstrap.yml to something else, it worked as expected. But if micronauts connects to consul first, the error is throwed.

https://github.com/lucasmogari/micronaut-flyway-test

Thanks for you attention.

**Comment by ilopmar** [comment] 2019-02-04 17:23
It turns out that this is actually an issue in micronaut-core: https://github.com/micronaut-projects/micronaut-core/issues/1215

**Comment by lucasmogari** [comment] 2019-02-04 17:44
Thank you! Both for the issue and the heads up about .mvn

**Comment by ilopmar** [comment] 2019-02-08 10:39
The issue has been fixed in Micronaut core.

**Closed by ilopmar** 2019-02-08 10:39 UTC
